### ISSUE TITLE
Rename principle-did

### ISSUE THREAD

**Issue by JanLin** [decentralised-dataexchange/automated-data-agreements#18]
Please rename "principle-did" to "data-subject-did" which aligns better with DID Method actors? Principle was a term used in ISO, "pii_principle" and nowhere is it used.

**Comment by georgejpadayatti** [comment]
@lalc Is this ok ?

**Comment by lalc** [comment]
Yes. 

To update the following:

- [ ] DA JSON schema
- [ ] DA JSON-LD
- [ ] The DA vocab

**Comment by georgejpadayatti** [comment]
and 

- [ ] DA Plugin (ACA-Py)

The changes from now on, are going to have considerable impact.

**Comment by JanLin** [comment]
Just realized all field names use "_" (underscore) and not "-" (dash). Is it too late to make it "data_subject_did"?

**Comment by georgejpadayatti** [comment]
> and
> 
> * [x]  DA Plugin (ACA-Py)
> 
> The changes from now on, are going to have considerable impact.

Done in DA plugin.

**Comment by lalc** [comment]
Is it ok to close this? @georgejpadayatti
